services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-cvdb}
      POSTGRES_USER: ${POSTGRES_USER:-cvuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-cvpass}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    restart: unless-stopped

  worker:
    build: .
    command: python manage.py run_celery_worker --worker-type all --concurrency 4
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    restart: unless-stopped
  
  beat:
    build: .
    command: python manage.py run_celery_beat --loglevel info
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    restart: unless-stopped
  
  flower:
    build: .
    command: celery -A CVProject flower --port=5555
    ports:
      - "5555:5555"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    restart: unless-stopped

volumes:
  pgdata: