from enum import Enum


class TimePreset(str, Enum):
    LAST_HOUR = "last_hour"
    LAST_24H = "last_24h"
    LAST_WEEK = "last_week"
    LAST_MONTH = "last_month"


class TimeOrder(str, Enum):
    ASC = "asc"
    DESC = "desc"


class Language(str, Enum):
    # Major world languages
    ENGLISH = "English"
    SPANISH = "Spanish"
    FRENCH = "French"
    GERMAN = "German"
    ITALIAN = "Italian"
    PORTUGUESE = "Portuguese"
    RUSSIAN = "Russian"
    CHINESE = "Chinese"
    JAPANESE = "Japanese"
    KOREAN = "Korean"
    ARABIC = "Arabic"
    HINDI = "Hindi"
    DUTCH = "Dutch"
    SWEDISH = "Swedish"
    NORWEGIAN = "Norwegian"
    DANISH = "Danish"
    FINNISH = "Finnish"
    POLISH = "Polish"
    CZECH = "Czech"
    HUNGARIAN = "Hungarian"
    ROMANIAN = "Romanian"
    BULGARIAN = "Bulgarian"
    CROATIAN = "Croatian"
    SERBIAN = "Serbian"
    SLOVAK = "Slovak"
    SLOVENIAN = "Slovenian"
    GREEK = "Greek"
    TURKISH = "Turkish"
    HEBREW = "Hebrew"
    PERSIAN = "Persian"
    URDU = "Urdu"
    BENGALI = "Bengali"
    TAMIL = "Tamil"
    TELUGU = "Telugu"
    MARATHI = "Marathi"
    GUJARATI = "Gujarati"
    KANNADA = "Kannada"
    MALAYALAM = "Malayalam"
    PUNJABI = "Punjabi"
    UKRAINIAN = "Ukrainian"
    BELARUSIAN = "Belarusian"
    LITHUANIAN = "Lithuanian"
    LATVIAN = "Latvian"
    ESTONIAN = "Estonian"
    GEORGIAN = "Georgian"
    ARMENIAN = "Armenian"
    AZERBAIJANI = "Azerbaijani"
    KAZAKH = "Kazakh"
    UZBEK = "Uzbek"
    KYRGYZ = "Kyrgyz"
    TAJIK = "Tajik"
    TURKMEN = "Turkmen"
    MONGOLIAN = "Mongolian"
    THAI = "Thai"
    VIETNAMESE = "Vietnamese"
    INDONESIAN = "Indonesian"
    MALAY = "Malay"
    TAGALOG = "Tagalog"
    SWAHILI = "Swahili"
    AMHARIC = "Amharic"
    YORUBA = "Yoruba"
    IGBO = "Igbo"
    HAUSA = "Hausa"
    ZULU = "Zulu"
    AFRIKAANS = "Afrikaans"
    ALBANIAN = "Albanian"
    MALTESE = "Maltese"
    ICELANDIC = "Icelandic"
    IRISH = "Irish"
    WELSH = "Welsh"
    SCOTTISH_GAELIC = "Scottish Gaelic"
    BASQUE = "Basque"
    CATALAN = "Catalan"
    GALICIAN = "Galician"
