# Generated by Django 5.2.6 on 2025-09-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('skills', models.TextField(blank=True)),
                ('projects', models.TextField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('contacts', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['lastname', 'firstname'],
            },
        ),
    ]
