# Generated by Django 5.2.6 on 2025-10-01 13:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_cv_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cv",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
