# Generated by Django 5.2.6 on 2025-10-01 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_analysislog"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AnalysisLog",
        ),
    ]
